### ISSUE TITLE
2 verschiedene Webseiten

### ISSUE THREAD

**Issue by boiselinum** [jboi-github/website4art#1]

**Comment by jboi-github** [comment]
Jeder artist hat nun eine eigene CSS-Datei. Der Name setzt sich zusammen aus `website4art/website4art/wwwroot/css/site-<artist>.css` und ist damit eindeutig per Artist.
Die aktuelle site.css wurde kopiert und der Hintergrund für Tests verändert.
Ist kein Artist angegeben wird die Datei `site-.css` angezogen.
